services:
  db:
    image: postgres:14.13-bullseye
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    ports:
      - "5432:5432"

  redis:
    image: redis:7.4.0
    networks:
      - app_network

  web:
    build:
      context: .
      args: # A seção args define variáveis de ambiente para o processo de build da imagem Docker
        RAILS_ENV: ${RAILS_ENV:-development}
    volumes:
      - .:/app
    restart: always
    ports:
      - "3000:3000"
    environment: # A seção environment define variáveis de ambiente no runtime
      REDIS_URL: redis://redis:6379/0
      RAILS_ENV: ${RAILS_ENV:-development}
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    depends_on:
      - db
      - redis
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
